### PR TITLE
Dom/base dc

### PR DESCRIPTION
**Pull request by fourndo**
Update the BaseDC with I/O and Utilis for DC.
Add speudo-section example in SimpegDCIP/Example

### CODE REVIEW

**Comment by rowanc1** [comment]
Will this be the final PR before we merge it into simpeg?

**Comment by fourndo** [comment]
No, Seogi will do a PR after mine has been merged into master... then we are ready to go.

**Comment by rowanc1** [comment]
Great! I will leave you to it. Can you send me an email when you two have merged everything in?

**Comment by fourndo** [comment]
Will do

**Pull request merged**
